name: Build Builder Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * *'

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        # TODO: parse from config
        include:
          - name: archlinux
            from: ghcr.io/clansty/archlinux:base-devel
            package-type: pacman
            platform: linux/amd64,linux/arm64,linux/riscv64
          - name: manjaro
            from: manjarolinux/base:latest
            package-type: pacman
            platform: linux/amd64,linux/arm64
          - name: ubuntu-22.04
            from: ubuntu:22.04
            package-type: deb
            platform: linux/amd64,linux/arm64,linux/riscv64
          - name: ubuntu-22.10
            from: ubuntu:22.10
            package-type: deb
            platform: linux/amd64,linux/arm64,linux/riscv64
          - name: ubuntu-20.04
            from: ubuntu:20.04
            package-type: deb
            platform: linux/amd64,linux/arm64,linux/riscv64
          - name: debian-11
            from: debian:11
            package-type: deb
            platform: linux/amd64,linux/arm64
          - name: debian-10
            from: debian:10
            package-type: deb
            platform: linux/amd64,linux/arm64
          - name: deepin-beige
            from: ghcr.io/clansty/deepin-riscv:latest
            package-type: deb
            platform: linux/riscv64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: builder
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/clansty/package-builder:${{ matrix.name }}
          build-args: |
            FROM=${{ matrix.from }}
            PACKAGE_TYPE=${{ matrix.package-type }}
